### ISSUE TITLE
Is the accessToken from loginPopup the same as from acquireTokenSilent?

### ISSUE THREAD

**Issue by dfibuch** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#23]
Please follow the issue template below. Failure to do so will result in a delay in answering your question.

## Library

- [x] `@azure/msal-browser@2.0.1`

## Description

Context: `msalApp = PublicClientApplication`

I'm just trying to figure out the flow of using the `accessToken` when calling my API from my SPA. The flow I have is to 
- User opens the SPA, `msalApp.Signin()` is called and I store the `account, username, accessToken, etc` in the context
- User then clicks to go to the next screen which calls the API with the `accessToken` which was obtained during the login process

However, I get a 401 response. If I call `msalApp.acquireTokenSilent()` and use the `accessToken` from this response, it works fine. 

So my question is am I supposed to call the `msalApp.acquireTokenSilent()` method before I make any API calls and just use the token directly the response and not worry about any local caching? I'm assuming this `msalApp` will handle all the token refreshing/caching for me and only get a new one if its expired?

In the past I've had to handle all this myself when I did some work with B2C.

**Comment by derisen** [comment]
@dfibuch not necessarily. In the sample, `msalApp.signIn()` is using the msal's `loginPopup()` API, which passes a set of scopes from the `loginRequest` object. However the web API in the sample expects a token with a different scope than the ones passed in during the login. That's why the access token obtained from `loginPopup()` won't work for the web API, since it doesn't contain the necessary scope.

Now the `acquireTokenSilent()` is just checking whether there is an access token in the cache (browser) with the right scopes. If there is none, it fall backs to interactively acquire one. But in general yes, this is the recommended pattern: do a silent request to see if there's an appropriate token in the cache. `msalApp` handles these things, but we also store the tokens in the Redux store for illustration purposes (of course, you shouldn't do that in production since Redux store might be compromised). 

You can read more about [resources and scopes here](https://github.com/AzureAD/microsoft-authentication-library-for-js/blob/dev/lib/msal-browser/docs/resources-and-scopes.md).

**Comment by dfibuch** [comment]
Thank you, this is very informative. I'm not planning on storing the token in any cache except for what `msalApp` does and just getting the token from it when I need to do a API call.

And the thing about scopes makes sense now, if I want my login request to give me a toke with the correct scope I just need to add my `api://...` scope to the list.

Thank you, I'll close this question now.
