### ISSUE TITLE
Getting Bearer error="invalid_token", error_description="The signature key was not found" in the example

### ISSUE THREAD

**Issue by lazydreamerbliss** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#31]
# Library

- @azure/msal-browser": "^2.1.0

# Description

I followed the example and get `Bearer error="invalid_token", error_description="The signature key was not found"` error in response when SPA request profile info from backend API, and I have no idea on how to resolve this because I checked everything and all looks good

# What I Have Done

I modified backend's port number to 5001 (https, `dev-cert` installed), and I can confirm everything bellow is correct

The backend API route path is `/api/profile/`

- SPA application
    - registered in AAD
    - client ID acquired
    - redirect URL for oauth added to AAD
    - API permission added (Backend API's "access_as_user")
    - `authConfig.js` fully configured, as followed:
```javascript
export const msalConfig = {
    auth: {
        clientId: "SPA'sclient ID",
        authority: "https://login.microsoftonline.com/consumers",
        redirectUri: "http://localhost:3000"
    }
}
export const apiConfig = {
    resourceUri: "https://localhost:5001/api/profile",
    resourceScope: "api://Backend API's client ID/access_as_user"
}
```

- Backend API application
    - registered in AAD
    - client ID acquired
    - client secret acquired
    - API permission added (for graph API) to AAD
    - API exposed for SPA, named "access_as_user", in AAD
    - Manifest file added SPA's client ID into list of `KnownClientApplications`
    - `appsettings.json` fully configured, as followed:
```json
"AzureAd": {
    "Domain": "my account domain in AAD",
    "ClientId": "Backend API's client ID",
    "ClientSecret": "Backend API's secret",
    "Instance": "https://login.microsoftonline.com/",
    "TenantId": "my tenant ID"
  },
```

# Error Info

The error occurs after a successful login, that when react SPA tries to call backend API to get profile info, the frontend logging is like this (I added logging info myself):
```
App.js:18 CLICK LOGIN
authProvider.js:116 DO SIGN IN
authProvider.js:78 HANDLE RESPONSE
authProvider.js:91 ACQUIRING TOKEN
App.js:21 SIGN IN FINISHED
ProfileContainer.jsx:25 TOKEN ACQUIRED
serviceActions.js:9 TRY TO GET PROFILE, SENDING ACCESS TOKEN TO BE
serviceActions.js:10 GET https://localhost:5001/api/profile/XXXX (401 Unauthorized)
```

I can see the token `Bearer XXXX` in the request header when SPA tries to GET profile info from backend, and the failed request's response is:
```
www-authenticate: Bearer error="invalid_token", error_description="The signature key was not found"
```

# The Token I Acquired in SPA

Here is a sample parsed token info that I acquired (after the successful login) and sent to backend API:
```
{
  "typ": "JWT",
  "alg": "RS256",
  "kid": "XXXX"
}
{
  "ver": "2.0",
  "iss": "https://login.microsoftonline.com/XXXX/v2.0",
  "sub": "XXXX",
  "aud": "I can confirm the audience here is backend API's client ID",
  "exp": 1601190191,
  "iat": 1601186291,
  "nbf": 1601186291,
  "name": "my name",
  "preferred_username": "my email",
  "oid": "my profile ID",
  "tid": "XXXX",
  "azp": "XXXX",
  "scp": "access_as_user",
  "azpacr": "0",
  "aio": "XXXX"
}
```

Any help would be really appreciated! I have been stuck on this for too long :(

**Comment by derisen** [comment]
@nonemaw I see an issue with the scope you define in your configuration file. In the sample, API scope is in the configuration is defined as `api://Backend API's client ID/.default`. The reason is that the [/.default scope](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#the-default-scope) allows user to give a combined consent to both the client and the web API. Could you change that part and try again? 

Also, try checking the **ID token** in the API's registration, as in: 

![screenshot](https://user-images.githubusercontent.com/13197548/94375012-6059fe80-00c5-11eb-82db-ba61bf088062.png)

**Comment by lazydreamerbliss** [comment]
@derisen Hi Derisen, thanks for the reply! I tried your suggestions but with no luck. I ticked the ID tokens options for SPA and changed the scope back to default, but same error still occurs.

BTW, the ID tokens options is for frontend SPA right? Because in the tutorial the authentication with redirect URL is only mentioned for SPA's registration, and backend API seems no need for this

**Comment by derisen** [comment]
@nonemaw Oh no it was for the web API's registration. SPA is using MSAL.js 2.x so it does not need/won't support implicit flow (API side is using MSAL.NET/M.I.W and things are a little different there). In case if that won't help, (1) can you send me your network trace? (using something like Fiddler -you can see my mail in my profile) (2) is there a public repo that I can take a look at?

**Comment by lazydreamerbliss** [comment]
@derisen Hi Derisen, thanks for the reply! I am checking the ID tokens option that you mentioned:
- The README.md does not mention about "Authentication" tab for Backend API, and seems only SPA should config "Authentication" with a redirect URL, which in our sample is `http://localhost:3000`
- The "ID tokens" implicit grant option is only available when "Authentication" has been configured with a redirect URL, therefore I was wandering if the "ID tokens" option is for SPA before.

Since you said the ID tokens is for Backend API then I need to config the "Authentication" tab for it, then which platform (and redirect URL) should I use? The README.md has no such guid for this part.

For question (1): I will share the trace after I fix the "ID tokens" issue for Backend API
For question (2): I also tried to run this repo directly with modifications only to configs and I still have no luck but have exactly same error message :(

**Comment by derisen** [comment]
@nonemaw you're right, there are no guides for checking ID token for backend API, as this is normally not needed (but in some cases it helps). Anyway, let's put that aside for a while, since you're saying even using the sample 'as is' is giving the same error. Sharing the network trace would be the best way to proceed.

**Comment by lazydreamerbliss** [comment]
@derisen Hi Derisen, the email with the attached trace has been delivered, Thanks in advance!

**Comment by derisen** [comment]
The issue was resolved over email correspondence. Closing.

**Comment by DkParasmal** [comment]
@nonemaw can you share here how you resolved this ?

**Comment by derisen** [comment]
@DkParasmal, the issue here was related to an incorrectly set `TenantId` in [appsettings.json](https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo/blob/master/ProfileAPI/appsettings.json). Make sure to leave it as "consumers" as this sample was configured to work with consumer accounts only. If you would like to use it with other types of accounts, see this: [How to configure this sample to allow sign-ins with work and school accounts](https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo/blob/master/ReadmeFiles/howto-common.md#how-to-configure-this-sample-to-allow-sign-ins-with-work-and-school-accounts)

If your problem persists, please open a new issue with your app details.
