### ISSUE TITLE
I was not able to get it working until I did these extra steps:

### ISSUE THREAD

**Issue by mehdipanjwani-ains** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#40]
I was not able to get it working until I did these extra steps:

1. App registrations > ProfileAPI > API permissions > Delegated permissions, allow openid and profile as well. It seems that in the authConfig.js loginRequest scopes, you need them.
2. App registrations > ProfileAPI > Expose an API > Authorized client applications > Add a client application. In Client ID paste the app Id of ProfileSPA and make sure you allow the scope of ProfileAPI Application ID URI.
3. App registrations > ProfileSPA > Authentication > select the "Access tokens" and "ID tokens" checkboxes.
4. When connecting it to enterprise account instead of personal accounts, App Registration > Authentication, select "Accounts in this organizational directory only (Single tenant)". Then change the authority to your tenant-id instead of the word "common". Change this on both the apps (ProfileSPA authConfig.js and ProfileAPI appSettings.json)

**Comment by derisen** [comment]
@mehdipanjwani-ains sorry for your trouble. I've made some changes to the sample just recently, which should help with these issues.

> I was not able to get it working until I did these extra steps:
> 
> 1. App registrations > ProfileAPI > API permissions > Delegated permissions, allow openid and profile as well. It seems that in the authConfig.js loginRequest scopes, you need them.

This shouldn't be needed, as Azure AD is able to do incremental consent i.e. users can consent to those scopes at run time. However, it doesn't hurt to add them explicitly so its fine.

> 2. App registrations > ProfileAPI > Expose an API > Authorized client applications > Add a client application. In Client ID paste the app Id of ProfileSPA and make sure you allow the scope of ProfileAPI Application ID URI.

This basically prevents the consent screen from coming up at all. In a single-tenant scenario, this is rather a matter of preference. With consumer accounts, this would be undesirable. 

Regardless, I've fixed the consent issue in the last PR, so the need for doing this shouldn't arise now.

> 3. App registrations > ProfileSPA > Authentication > select the "Access tokens" and "ID tokens" checkboxes.

These boxes should be left unchecked, as the current version of the sample is using [authorization code flow with PKCE](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-auth-code-flow) instead of [implicit flow](https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-oauth2-implicit-grant-flow).

> 4. When connecting it to enterprise account instead of personal accounts, App Registration > Authentication, select "Accounts in this organizational directory only (Single tenant)". Then change the authority to your tenant-id instead of the word "common". Change this on both the apps (ProfileSPA authConfig.js and ProfileAPI appSettings.json)

I've just revised the README to highlight this point a little better. There is a [short guide in ReadmeFiles](https://github.com/Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo/blob/master/ReadmeFiles/howto-common.md) regarding this.

Let me know if you need any help.

**Comment by derisen** [comment]
Closing. Feel free to reopen if you need further help.
