### ISSUE TITLE
Getting this sample to with a single-tenant account e.g. company account

### ISSUE THREAD

**Issue by jpro1001** [Azure-Samples/ms-identity-javascript-react-spa-dotnetcore-webapi-obo#5]
Hi,

Anyone know why this sample has a note that says it won't work with an Azure work account? I'm struggling really hard on trying to get a React SPA to call a .NET Core Web API with Azure authentication. I'm wondering if I'm missing something fundamental with OAuth and single-tenant accounts. I was able to change the config files to use my tenant ID and my azure app domain to login successfully. I believe I also enabled Access Tokens as well. However, it fails when trying to access the graph user profile on this line:

line 85: ProfileController.cs
It's receiving a GUID as the profile.Id, but it's trying to modify it with 0s and the ID string is longer than expected and is trying to use a -4 to append 0s and fails.

I'm still trying to figure out the details, but is this possible with a work account?

Note talking about:
[!NOTE] This sample is configured to allow sign-ins with personal Microsoft accounts ONLY using the /consumers endpoint. Learn more about supported account types and validation differences between them.

Thank you guys very much for making this sample. This is helping me learn Azure Identity at lot. Any help or direction on where to go from here would be greatly appreciated!

**Comment by derisen** [comment]
@jpro1001 sorry for the delay. The note about azure work accounts is entirely due to this particular scenario and how the sample was configured. Other than that, there is nothing preventing you from using it with work accounts, with a little bit of modification. 

So the first thing to change is to use the **tenanted enpoint** (i.e. with your tenantId), instead of the `/customers` endpoint (works only with personal MS accounts). 

In `ProfileAPI\appsettings.json`:

```json
    "AzureAd": {
        "Domain": "msaltestingjs.onmicrosoft.com",
        "ClientId": "YOUR_CLIENT_ID",
        "ClientSecret": "YOUR_CLIENT_SECRET",
        "Instance": "https://login.microsoftonline.com/",
        "TenantId": "YOUR_TENANT_ID"
    },
```


Then in `ProfileSPA\src\utils\authConfig.js`:
```javascript
    auth: {
        clientId: "YOUR_CLIENT_ID",
        authority: "https://login.microsoftonline.com/YOUR_TENANT_ID",
        validateAuthority: true,
        redirectUri: "http://localhost:3000",
        navigateToLoginRequestUrl: false
    },
```

And finally, get rid of the ID crunching logic in `line 85: ProfileController.cs` (which we only used because of how object Id is represented for personal MS accounts)

```csharp
                    // int x = 32 - profile.Id.Length;
                    // string graphID = new string('0', x) + profile.Id;

                    profileItem.Id = profile.Id;
                    ...
```

You should then be good to go. Let me know if there are any issues.

**Comment by jpro1001** [comment]
Thank you! Also, I noticed the .NET authentication library "Microsoft.Identity.Web" appears to be in preview. Do you happen to know when this will be ready for use in production?

**Comment by derisen** [comment]
@jpro1001 no worries : ) Unfortunately, no set date for when Microsoft.Identity.Web will be production ready. However it is built upon MSAL.NET, which is quite mature at this point. You can see their [roadmap here](https://github.com/AzureAD/microsoft-identity-web/wiki).

**Comment by jmprieur** [comment]
@jpro1001 : we want to release MIcrosoft.Identity.Web GA with .NET 5.0
cc: @derisen
